### ISSUE TITLE
The question of how to install colmap

### ISSUE THREAD

**Issue by ThePrecoder** [weiyithu/NerfingMVS#19]
I'm sorry to bother you sir.I'm a student interested in your code,but  I just don't know how to install it.
Before installing it into colmap folder,should I add 
![image](https://user-images.githubusercontent.com/89020229/142868294-337a62f6-deb1-47ca-9e6a-082226209460.png)
into it first?And then just follow the basic step to install the colmap into it without covering these files?I just don't understand what "do not cover colmap folder with the original version" and "we add masks to COLMAP and denote it as a submodule"means.I'm so looking forward to your reply.

**Comment by ThePrecoder** [comment]
![image](https://user-images.githubusercontent.com/89020229/142873510-0fe67e15-b4db-4a84-b0c7-a129ba99305c.png)
this is what I downloaded,should I just copy it into colmap folder?Im a freshman,so sorry to bother you.

**Comment by weiyithu** [comment]
It means that we modify the original COLMAP and update some functions. When you "git clone --recursive git@github.com:weiyithu/NerfingMVS.git", you have already downloaded our version's COLMAP. However, what you download is the source code and you need to compile it following  https://colmap.github.io/install.html. Notice that do not run 'git clone https://github.com/colmap/colmap.git' and 'git checkout dev' since these two commands will cover the colmap folder. You may refer to #15 .

**Comment by ThePrecoder** [comment]
> It means that we modify the original COLMAP and update some functions. When you "git clone --recursive [git@github.com](mailto:git@github.com):weiyithu/NerfingMVS.git", you have already downloaded our version's COLMAP. However, what you download is the source code and you need to compile it following https://colmap.github.io/install.html. Notice that do not run 'git clone https://github.com/colmap/colmap.git' and 'git checkout dev' since these two commands will cover the colmap folder. You may refer to #15 .

Thanks a lot,I'll try later.

**Comment by ThePrecoder** [comment]
> It means that we modify the original COLMAP and update some functions. When you "git clone --recursive [git@github.com](mailto:git@github.com):weiyithu/NerfingMVS.git", you have already downloaded our version's COLMAP. However, what you download is the source code and you need to compile it following https://colmap.github.io/install.html. Notice that do not run 'git clone https://github.com/colmap/colmap.git' and 'git checkout dev' since these two commands will cover the colmap folder. You may refer to #15 .

Sorry but,when I run "make"after "cmake ..",it occurs
![image](https://user-images.githubusercontent.com/89020229/143232944-87ae7f2a-ffb1-4850-bde4-f748ca22061e.png)

I dont know what happened.

**Comment by weiyithu** [comment]
Could you provide more details?

**Comment by ThePrecoder** [comment]
> Could you provide more details?
That error was resolved,
when I run "sh run.sh $scene_name",it occurs
![image](https://user-images.githubusercontent.com/89020229/143441550-613f3276-b8ce-469b-b1bd-6e90e85434ca.png)
did that mean the memory was used  up.

**Comment by weiyithu** [comment]
Yeah, it is out of memory.

**Comment by ThePrecoder** [comment]
> Yeah, it is out of memory.

![1637914704(1)](https://user-images.githubusercontent.com/89020229/143549235-aaa7871e-d8c1-432b-8d22-0aa8ecd7734e.png)
what happened to this...it said" unpack requires a buffer of 12 bytes"when loaded point_vis

**Comment by weiyithu** [comment]
It may because you used original COLMAP instead of our version's. You can refer to #15 and #2

**Comment by ThePrecoder** [comment]
> 

okay,I've seen that.thanks a lot,Im sorry for not getting you back for so long.These days I was busy doing my tasks.

**Comment by ThePrecoder** [comment]
> It may because you used original COLMAP instead of our version's. You can refer to #15 and #2

My problem is resolved,thank you so much and have a happy day.

**Comment by ThePrecoder** [comment]
> It may because you used original COLMAP instead of our version's. You can refer to #15 and #2

My problem is solved,thank you so much.

**Comment by weiyithu** [comment]
Oh, that's great.

**Comment by ygjwd12345** [comment]
I also face the same problem. I install colmap for https://github.com/B1ueber2y/colmap.git. But the problem still exists.

**Comment by nitishkiitk** [comment]
> Oh, that's great.
Dear author the error of the byte is not fixed can you help or can you provide the actual installation process?
unpack requires a buffer of 12 bytes
